org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=oretrees
mod_name=OreTrees
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.nftl
mod_authors=NeofastFTL (decompiled rebuild)
mod_description=Grow your resources instead of mining them. Ore trees that produce acorns, resin and amber.
